name: Spring Boot maven project CI/CD with GitHub Actions

# This workflow is triggered on pushes to the repository and pull requests to the repository to main and develop branches
on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

# jobs: A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code --> downloading the code resource
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn clean 
        mvn -Dmaven.test.skip=true -B install 
        mvn -Dmaven.test.skip=true -B package --file pom.xml

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code --> downloading the code resource
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run:
            mvn clean test

